FROM golang:1.10-stretch

MAINTAINER Gabriel Garrido

RUN wget "https://s3.eu-central-1.amazonaws.com/lightstreams-public/lightchain/latest/lightchain-linux-amd64" -O "/usr/bin/lightchain"
RUN chmod a+x /usr/bin/lightchain

COPY ./scripts/docker.sh /root/init.sh
RUN chmod a+x /root/init.sh
ENTRYPOINT ["/root/init.sh"]

EXPOSE 8545 26657 26656
