[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.18"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "^v0.11.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "^0.27.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "~0.14.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.1"

[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "^0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[prune]
  go-tests = true
